language: python
before_install:
  - sudo apt-get install gettext
  - sudo apt-get install redis-server
  - sudo service redis-server start
install:
  - pip install coveralls
  - pip install 'setuptools>=33,<34'
  - pip install -r requirements.txt
script:
  - cd transifex && make test_coverage
after_success:
  - coveralls
